### ISSUE TITLE
[Request]: add software dopus

### ISSUE THREAD

**Issue by cheng1nuo** [xrgzs/sdoog#13]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Criteria 1
- [X] Criteria 2
- [X] Criteria 3

### Name

Directory Opus

### Description

A complete replacement for Explorer, with far more functionality than any other file manager available today

### Homepage

https://www.gpsoft.com.au/

### Download Link(s)

https://cdn.gpsoft.com.au/files/Opus13/Beta/DOpusInstall-13.10.5.Beta.exe

### Some Indication of Popularity/Repute

A complete replacement for Explorer, with far more functionality than any other file manager available today

**Comment by xrgzs** [comment]
https://github.com/xrgzs/sdoog/commit/e1d5b0463a080f699ad8ba248e72efd5549eac5b

```
scoop install directoryopus-np
```

**Comment by xrgzs** [comment]
网络不好，麻烦帮我试试看有没有问题

**Comment by cheng1nuo** [comment]
aira2  Timeout Unable to download file😅

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
